In [6]:
import sleap
import numpy as np
import matplotlib.pyplot as plt
import os, sys

sys.path.append('..')
from src.data_loader import *
from min2.run_models import *

In [9]:
def roll_coords(coords):
    assert coords.ndim == 3, 'coords must be a 3D array with shape (frame_cnt, pt_cnt, 2)'
    pt_cnt = coords.shape[1]
    # each rolled version is treated as a new frame; return a list of 17 coords
    rolled_coords = [coords]
    for i in range(1, pt_cnt):
        rolled_coords.append(np.roll(coords, i, axis=1))
    return rolled_coords

In [14]:
coords = np.arange(24).reshape(4, 3, 2)
rolled_coords = roll_coords(coords)
print(len(rolled_coords))
print(rolled_coords[0])
print('--------')
print(rolled_coords[1])

3
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
--------
[[[ 4  5]
  [ 0  1]
  [ 2  3]]

 [[10 11]
  [ 6  7]
  [ 8  9]]

 [[16 17]
  [12 13]
  [14 15]]

 [[22 23]
  [18 19]
  [20 21]]]


In [12]:
rolled_coords_concat = np.concatenate(rolled_coords, axis=0)
rolled_coords_concat.shape

(12, 3, 2)

In [16]:
rolled_coords_unrolled = np.split(rolled_coords_concat, 3)
print(len(rolled_coords_unrolled))
print(rolled_coords_unrolled[0].shape)

3
(4, 3, 2)


In [17]:
rolled_coords_unrolled_concat = np.concatenate(rolled_coords_unrolled, axis=0)
rolled_coords_unrolled_concat.shape

(12, 3, 2)